config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'home#index'
  get 'home/index'
  resources :poets
  get 'likes/create'
  devise_for :users
  resources :poems
  
  get '/search' => 'poets#search'
  post 'poems/:poem_id/likes' => 'likes#create'
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :poem
end

app/models/poem.rb
class Poem < ApplicationRecord
    belongs_to :user
    has_one_attached :picture
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    belongs_to :poet, optional: true
end

app/models/poet.rb
class Poet < ApplicationRecord
    belongs_to :user
    has_one_attached :portrait
    has_many :poems
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :poems
         has_many :likes
         has_many :liked_poems, through: :likes, source: :poem
         has_many :poets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @like = Like.find_by(poem_id: params[:poem_id], user_id: current_user.id)
    
    if @like.present?
      @like.destroy
      @like = nil
    else
      @like = Like.create(poem_id: params[:poem_id], user_id: current_user.id)
    end
    
    @poem = Poem.find(params[:poem_id])
    @like_count = @poem.likes.count
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_permission, only: [:edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @pagy, @poems = pagy(Poem.all, items:9)
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    if poem_params[:title].empty?
      redirect_to(request.referrer, notice: "제목이 비었습니다.") and return
    elsif  poem_params[:body].empty?
      redirect_to(request.referrer, notice: "본문이 비었습니다.") and return
    end

    @matchPoet = Poet.all.where("name = ? ", "#{params[:poem][:poet]}")
    if @matchPoet == nil
      redirect_to(request.referrer, notice: "시인이 존재하지 않습니다.") and return
    elsif @matchPoet.length > 1
      redirect_to(request.referrer, notice: "시인이 중복되어 존재합니다.") and return
    end
    
    @poem = Poem.new(poem_params)
    @poem.user_id = current_user.id
    @poem.poet = @matchPoet.first

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end    
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    @matchPoet = Poet.all.where("name = ? ", "#{params[:poem][:poet]}")
    if @matchPoet == nil
      redirect_to(request.referrer, notice: "시인이 존재하지 않습니다.") and return
    elsif @matchPoet.length > 1
      redirect_to(request.referrer, notice: "시인이 중복되어 존재합니다.") and return
    end
    @poem.poet = @matchPoet.first

    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.likes.clear
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poem_params
      params.require(:poem).permit(:title, :body, :year, :description, :picture)
    end
    
    def require_permission
      if current_user != @poem.user
        redirect_to root_path, notice: 'You don\'t have a permission for this post'
      end
    end

end

app/controllers/poets_controller.rb
class PoetsController < ApplicationController
  before_action :set_poet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :require_permission, only: [:edit, :update, :destroy]

  def search
    if params[:search].blank?
      redirect_to(request.referrer, notice: "검색란이 비었습니다.") and return
    else
      @parameter = params[:search].downcase
      @matchPoets = Poet.all.where("lower(name) LIKE ?", "%#{@parameter}%")
      @matchPoems = Poem.all.where("lower(title) LIKE ?", "%#{@parameter}%")
    end
  end

  # GET /poets
  # GET /poets.json
  def index    
    @pagy, @poets = pagy(Poet.all, items: 9)
  end

  # GET /poets/1
  # GET /poets/1.json
  def show
  end

  # GET /poets/new
  def new
    @poet = Poet.new
  end

  # GET /poets/1/edit
  def edit
  end

  # POST /poets
  # POST /poets.json
  def create
    @poet = Poet.new(poet_params)
    @poet.user_id = current_user.id

    respond_to do |format|
      if @poet.save
        format.html { redirect_to @poet, notice: 'Poet was successfully created.' }
        format.json { render :show, status: :created, location: @poet }
      else
        format.html { render :new }
        format.json { render json: @poet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poets/1
  # PATCH/PUT /poets/1.json
  def update
    respond_to do |format|
      if @poet.update(poet_params)
        format.html { redirect_to @poet, notice: 'Poet was successfully updated.' }
        format.json { render :show, status: :ok, location: @poet }
      else
        format.html { render :edit }
        format.json { render json: @poet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poets/1
  # DELETE /poets/1.json
  def destroy
    @poet.destroy
    respond_to do |format|
      format.html { redirect_to poets_url, notice: 'Poet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poet
      @poet = Poet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poet_params
      params.require(:poet).permit(:name, :birthplace, :birthyear, :description, :portrait)
    end

    def require_permission
      if current_user != @poet.user
        redirect_to root_path, notice: 'You don\'t have a permission for this post'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
    def poem_liked_by_user?(poem, user)
        if user == nil
            return false
        else
            like = Like.find_by(poem_id: poem.id, user_id: user.id )
            return like.present? ? true : false
        end
    end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/poets_helper.rb
module PoetsHelper
end

app/views/home/index.html.erb
<%# <%= image_tag('home-image-poet.jpg')% > % >
<%# VISUAL %>
<section class="section section-visual">
    <div class="inner">
        <div class="todaypoet">
            <div class="todaypoet-title">서시</div>
            <div class="todaypoet-description">
            죽는 날까지 하늘을 우러러 <br>
            한점 부끄러움이 없기를 <br>
            잎새에 이는 바람에도 나는 괴로워했다. <br>
            <br>
            별을 노래하는 마음으로 모든 죽어가는 것들을 사랑해야지. <br>
            그리고 나에게 주어진 길을 걸어가야 겠다. <br>
            <br>
            오늘도 별이 바람에 스치운다. <br>
            </div>
        </div>
        <%# 나중에 "직접 작가가 되어 주세요!"란 문구 아래 로그인을 유도하자.  %>
        <%# <form action="" class="sign-form"></form> %>    
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ko">
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>TodayPoetry</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--font awesome -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/home">詩</a>            
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">        
        <ul class="navbar-nav mr-auto" >
          <li class="nav_item">
            <a class="nav-link" href="/poets">詩人들</a>
          </li>
          <li class="nav_item">
            <a class="nav-link" href="/poems">오늘의 詩</a>
          </li>
        </ul>
        <div style= "margin-right:15px;">
          <span class="navbar-text" id="notice"><%= notice %></span>
          <% unless user_signed_in? %>
            <a href="/users/sign_up">
                <span class="badge badge-light">회원가입</span>
            </a>
            <a href="/users/sign_in">
                <span class="badge badge-dark">로그인</span>
            </a>
          <% else %>            
            <span>&emsp;<%= current_user.email %>님</span>
            <a href="/users/edit">
                <span class="badge badge-light">내정보</span>
            </a>
            <%= link_to "로그아웃", destroy_user_session_path, method: "delete", class: "badge badge-dark" %>
          <% end %>        
        </div>
        
        <%= form_tag(search_path, :method => "get") do %>
          <div class="input-group">
            <%= search_field_tag :search, params[:search], placeholder: "시 또는 시인", class: "form-control mr-sm-2" %>
            <div class="input-group-btn">
              <%= button_tag "시/시인 찾기", :class => 'btn btn-outline-success glyphicon glyphicon-search', :name => nil %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/create.js.erb
$('body p#like_count > span').html('<%= @like_count %>')
$('body p#like_heart > a').html('<%= @like.present? ? "❤️" : "🤍" %>')

app/views/poems/_form.html.erb
<%= form_with(model: poem, local: true) do |form| %>
  <% if poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title, class: "col-form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :poet, class: "col-form-label" %>
    <%= form.text_field :poet, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :body, class: "col-form-label" %>
    <%= form.text_area :body, class: "form-control", rows: "15" %>
  </div>

  <div class="field form-group">
    <%= form.label :year, class: "col-form-label" %>
    <%= form.number_field :year, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description, class: "col-form-label" %>
    <%= form.text_area :description, class: "form-control", rows: "15"%>
  </div>

  <div class="field form-group">
    <%= form.label :picture, class: "col-form-label" %>
    <%= form.file_field :picture, class: "form-control-file"%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<div class="container">
    <div style="margin-top:50px; text-align:center;">
        <h1>詩 수정하기</h1>
    </div>
    <hr>
    <%= render 'form', poem: @poem %>
    <div style="margin-top:30px; text-align:right;">
        <a href="/poems">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>

app/views/poems/index.html.erb
<div class="container">
  <h1 style="margin-top:15px;">詩의 바다</h1>
      <div class="row">
          <% @poems.each do |poem| %>
                  <div class="card col-md-4 card-square">
                    <a href="<%= poem_path(poem) %>" style="color: #000000; text-decoration:none;">
                      <div class="card-body">
                        <div style="text-align:center;">
                          <h4 class="card-title"><%= poem.title %></h5>                        
                        <hr>
                        <p class="card-text">
                        <% if poem.body != nil %>
                        <%= poem.body.lines.first %><br> 
                        <%= poem.body.lines.second %>  
                        <% end %>
                        </p>
                        </div>
                    </a><br>
                        <div style="text-align:center; text-decoration:none;">
                            <% if user_signed_in? %>
                                <% if poem.user_id == current_user.id %>
                                  <a href="<%= edit_poem_path(poem) %>" >
                                    <span class="badge badge-warning">수정</span>
                                  </a>
                                  <a data-confirm="정말로 삭제하시겠습니까?" rel="nofollow" data-method="delete" href="<%= poem_path(poem) %>">
                                    <span class="badge badge-danger">삭제</span>
                                  </a>
                                <% end %>
                            <% end %>
                        </div>
                      </div>
                  </div>
          <% end %>
      </div>
      <hr>
      <div>
        <%== pagy_bootstrap_nav(@pagy) %>
        <script>
            Pagy.init()
        </script>
      </div>
      <div style="margin-top:30px; text-align:right;">
        <a href="<%= new_poem_path %>">
          <button type="button" class="btn btn-dark">새로운 시 올리기</button>
        </a>
      </div>
</div>

app/views/poems/new.html.erb
<div class="container">
    <div style="margin-top:50px; text-align:center;">
        <h1>詩 올리기</h1>
    </div>
    <hr>
    <%= render 'form', poem: @poem %>
    <div style="margin-top:30px; text-align:right;">
        <a href="/poems">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>

app/views/poems/show.html.erb
<div class="container">
    <div class="poem-title">
      <%= @poem.title %>
    </div>
    <div class="poet-name">
      <% if @poem.poet != nil %>
      <%= @poem.poet.name %>
      <% else %>
      작자 미상
      <% end %>
    </div>    
    <hr>
    <div class="poem-picture" >
    <% if @poem.picture.attached? %>
      <p>
        <%= image_tag @poem.picture %>
      </p>
      <hr>
    <% end %>
    </div>
    <div class="poem-web-info">
        <% if user_signed_in? %>
          <% if @poem.user_id == current_user.id %>
          <a href="/poems/<%= @poem.id %>/edit">
              <span class="badge badge-warning">수정</span>
          </a>
          <a href="/poems/<%= @poem.id %>" data-confirm="정말로 삭제하시겠습니까?" rel="nofollow" data-method="delete" >
              <span class="badge badge-danger">삭제</span>
          </a>
          <% end %>
        <% end %>
        <div style="margin-top:5px;">
            <div><%= @poem.user.email %></div>
            <div><%= @poem.created_at.to_s.split("+").first %></div>
        </div>
    </div>
    <div class="poem-body">
        <%= simple_format(@poem.body) %>
    </div>
    <hr>
    <div>
      <p id="like_count">
        <strong>좋아요 수</strong>
        <span><%= @poem.liked_users.count %></span>
      </p>
    <% if user_signed_in? %>
      <p id="like_heart">
          <%= link_to "#{poem_liked_by_user?(@poem, current_user) ? "❤️":"🤍" }","/poems/#{@poem.id}/likes", method: :post, remote: true %>
      </p>
    <% else %>
      <p>
        <%= link_to "🤍","/poems/#{@poem.id}/likes", method: :post %>
      </p>
    <% end %>
    </div>
    <hr>
    <div class="poem-description">
      <p>
        <span>연도 : </span><%= @poem.year %><br>
        <br><strong>시에 대한 설명</strong><br>
        <br><%= @poem.description %><br>
      </p>
    </div>
    <div class="go-back-btn">
        <a href="/poems">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>

app/views/poets/_form.html.erb
<%= form_with(model: poet, local: true) do |form| %>
  <% if poet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poet.errors.count, "error") %> prohibited this poet from being saved:</h2>

      <ul>
      <% poet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :portrait, class: "col-form-label" %>
    <%= form.file_field :portrait, class: "form-control-file" %>
  </div>
  
  <div class="field form-group">
    <%= form.label :name, class: "col-form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :birthplace, class: "col-form-label" %>
    <%= form.text_field :birthplace, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :birthyear, class: "col-form-label" %>
    <%= form.number_field :birthyear, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description, class: "col-form-label" %>
    <%= form.text_area :description, class: "form-control", rows: "15" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/poets/edit.html.erb
<div class="container">
    <div style="margin-top:50px; text-align:center;">
        <h1>詩人 수정하기</h1>
    </div>
    <hr>
    <%= render 'form', poet: @poet %>
    <div style="margin-top:30px; text-align:right;">
        <a href="/poets">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>

app/views/poets/index.html.erb
<div class="container">
  <h1 style="margin-top:15px;">詩人들</h1>
      <div class="row">
          <% @poets.each do |poet| %>
                  <div class="card col-md-4 card-square">
                    <a href="<%= poet_path(poet) %>" style="color: #000000; text-decoration:none;">
                      <div class="card-body">
                        <div style="text-align:center;">
                          <h4 class="card-title"><%= poet.name %></h5>
                        <hr>
                        <p class="card-text">
                        <% if poet.description != nil %>
                        <%= poet.description.split[0...30].join(' ') %>...
                        <% end %>
                        </p>
                        </div>
                    </a><br>
                        <div style="text-align:center; text-decoration:none;">
                            <% if user_signed_in? %>
                                <% if poet.user_id == current_user.id %>
                                  <a href="<%= edit_poet_path(poet) %>" >
                                    <span class="badge badge-warning">수정</span>
                                  </a>
                                  <a data-confirm="정말로 삭제하시겠습니까?" rel="nofollow" data-method="delete" href="<%= poet_path(poet) %>">
                                    <span class="badge badge-danger">삭제</span>
                                  </a>
                                <% end %>
                            <% end %>
                        </div>
                      </div>
                  </div>
          <% end %>
      </div>
      <hr>
      <div>
        <%== pagy_bootstrap_nav(@pagy) %>
        <script>
            Pagy.init()
        </script>
      </div>
      <div style="margin-top:30px; text-align:right;">
        <a href="<%= new_poet_path %>">
          <button type="button" class="btn btn-dark">새로 시인 기록하기</button>
        </a>
      </div>
</div>

app/views/poets/new.html.erb
<div class="container">
    <div style="margin-top:50px; text-align:center;">
        <h1>詩人 기록하기</h1>
    </div>
    <hr>
    <%= render 'form', poet: @poet %>
    <div style="margin-top:30px; text-align:right;">
        <a href="/poets">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>

app/views/poets/search.html.erb
<h3>검색 결과</h3>

<% if @matchPoets.length == 0 && @matchPoems.length == 0 %>
  검색된 시인이나 시가 없습니다. 
<% else %>
  <% if @matchPoets.length > 0 %>
    <h4>검색된 시인</h4>
      <% @matchPoets.each do |poet| %>

      <%= link_to poet.name, poet_path(poet.id) %>
      <% end %> 
    <br><br>
  <% end %>  
  <% if @matchPoems.length > 0 %>
    <h4>검색된 시</h4>
      <% @matchPoems.each do |poem| %>    
      <%= link_to poem.title, poem_path(poem.id) %>
      <% end %>
  <% end %>
<% end %>

app/views/poets/show.html.erb
<div class="container">
    <div class="poem-title">
      <%= @poet.name %>
    </div>    
    <hr>
    <div class="row">
      <div class="col-md-6">
            <div class="poem-picture poet-portrait-box" >
            <% if @poet.portrait.attached? %>
                <%= image_tag @poet.portrait, class: "poet-portrait" %>              
            <% end %>
            </div>
            <div class="poem-web-info poet-birth-info">
              <p>
                <strong>출생지_</strong>
                <%= @poet.birthplace %>
              </p>
              <p>
                <strong>출생년도_</strong>
                <%= @poet.birthyear %>
              </p>
            </div>
      </div>
      <div class="col-md-6">
        <div class="poem-body">
            <%= simple_format(@poet.description) %>
        </div>
        <div class="poem-web-info">
          <% if user_signed_in? %>
            <% if @poet.user_id == current_user.id %>
            <a href="/poets/<%= @poet.id %>/edit">
                <span class="badge badge-warning">수정</span>
            </a>
            <a href="/poets/<%= @poet.id %>" data-confirm="정말로 삭제하시겠습니까?" rel="nofollow" data-method="delete" >
                <span class="badge badge-danger">삭제</span>
            </a>
            <% end %>
          <% end %>
          <div style="margin-top:5px;">
              <div><%= @poet.user.email %></div>
              <div><%= @poet.created_at.to_s.split("+").first %></div>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <% @poet.poems.each do |poem| %>
              <div class="card col-md-4 card-square">
                <a href="<%= poem_path(poem) %>" style="color: #000000; text-decoration:none;">
                  <div class="card-body">
                    <div style="text-align:center;">
                      <h4 class="card-title"><%= poem.title %></h5>                        
                    <hr>
                    <p class="card-text">
                    <% if poem.body != nil %>
                    <%= poem.body.lines.first %><br> 
                    <%= poem.body.lines.second %>  
                    <% end %>
                    </p>
                    </div>
                </a><br>
                    <div style="text-align:center; text-decoration:none;">
                        <% if user_signed_in? %>
                            <% if poem.user_id == current_user.id %>
                              <a href="<%= edit_poem_path(poem) %>" >
                                <span class="badge badge-warning">수정</span>
                              </a>
                              <a data-confirm="정말로 삭제하시겠습니까?" rel="nofollow" data-method="delete" href="<%= poem_path(poem) %>">
                                <span class="badge badge-danger">삭제</span>
                              </a>
                            <% end %>
                        <% end %>
                    </div>
                  </div>
              </div>
      <% end %>
    </div>
    <hr>    
    <div class="go-back-btn">
        <a href="/poets">
            <button type="button" class="btn btn-dark">목록으로</button>
        </a>
    </div>
</div>